CREATE OR REPLACE TABLE GOLD.DIM_PATIENT AS
SELECT
    SHA2(TO_VARCHAR(c.SUBJECT_ID), 256) AS PATIENT_SK,
    c.SUBJECT_ID,
    MAX(c.GENDER) AS GENDER,
    MAX(c.ANCHOR_AGE) AS ANCHOR_AGE,
    MAX(c.ANCHOR_YEAR) AS ANCHOR_YEAR,
    MAX(c.ANCHOR_YEAR_GROUP) AS ANCHOR_YEAR_GROUP,
    MAX(c.RACE) AS RACE,
    CURRENT_TIMESTAMP() AS CREATED_AT,
    CURRENT_TIMESTAMP() AS UPDATED_AT
FROM SILVER.ICU_COHORT_CLEAN c
WHERE c.SUBJECT_ID IS NOT NULL
GROUP BY c.SUBJECT_ID;
