CREATE OR REPLACE TABLE GOLD.DIM_ADMISSION AS
SELECT
    SHA2(TO_VARCHAR(c.HADM_ID), 256) AS ADMISSION_SK,
    c.HADM_ID,
    MAX(c.ADMITTIME) AS ADMITTIME,
    MAX(c.DISCHTIME) AS DISCHTIME,
    MAX(c.DEATHTIME) AS DEATHTIME,
    MAX(c.ADMISSION_TYPE) AS ADMISSION_TYPE,
    MAX(c.ADMISSION_LOCATION) AS ADMISSION_LOCATION,
    MAX(c.DISCHARGE_LOCATION) AS DISCHARGE_LOCATION,
    MAX(c.INSURANCE) AS INSURANCE,
    MAX(c.LANGUAGE) AS LANGUAGE,
    MAX(c.MARITAL_STATUS) AS MARITAL_STATUS,
    CURRENT_TIMESTAMP() AS CREATED_AT,
    CURRENT_TIMESTAMP() AS UPDATED_AT
FROM SILVER.ICU_COHORT_CLEAN c
WHERE c.HADM_ID IS NOT NULL
GROUP BY c.HADM_ID;
