CREATE OR REPLACE TABLE GOLD.DIM_STAY AS
SELECT
    SHA2(TO_VARCHAR(c.STAY_ID), 256) AS STAY_SK,
    c.STAY_ID,
    c.SUBJECT_ID,
    c.HADM_ID,
    c.FIRST_CAREUNIT,
    c.LAST_CAREUNIT,
    c.INTIME,
    c.OUTTIME,
    c.LOS,
    CURRENT_TIMESTAMP() AS CREATED_AT,
    CURRENT_TIMESTAMP() AS UPDATED_AT
FROM SILVER.ICU_COHORT_CLEAN c
WHERE c.STAY_ID IS NOT NULL;
