CREATE OR REPLACE TABLE GOLD.DIM_LAB_COMPONENT AS
SELECT
    SHA2(TO_VARCHAR(s.ITEMID) || '|' || COALESCE(s.SOFA_COMPONENT, ''), 256) AS LAB_COMPONENT_SK,
    s.ITEMID,
    s.SOFA_COMPONENT,
    MAX(s.VALUEUOM) AS VALUEUOM,
    CURRENT_TIMESTAMP() AS CREATED_AT,
    CURRENT_TIMESTAMP() AS UPDATED_AT
FROM SILVER.LABEVENTS_SOFA_CLEAN s
WHERE s.ITEMID IS NOT NULL
GROUP BY s.ITEMID, s.SOFA_COMPONENT;
