SELECT 'PATIENTS_CLEAN' AS table_name, COUNT(*) AS row_count FROM SILVER.PATIENTS_CLEAN
UNION ALL
SELECT 'ADMISSIONS_CLEAN', COUNT(*) FROM SILVER.ADMISSIONS_CLEAN
UNION ALL
SELECT 'ICUSTAYS_CLEAN', COUNT(*) FROM SILVER.ICUSTAYS_CLEAN
UNION ALL
SELECT 'DIAGNOSES_CLEAN', COUNT(*) FROM SILVER.DIAGNOSES_CLEAN;