SELECT COUNT(*) AS null_subject_ids
FROM SILVER.PATIENTS_CLEAN
WHERE SUBJECT_ID IS NULL;

SELECT COUNT(*) AS null_hadm_ids
FROM SILVER.ADMISSIONS_CLEAN
WHERE HADM_ID IS NULL;

SELECT COUNT(*) AS null_stay_ids
FROM SILVER.ICUSTAYS_CLEAN
WHERE STAY_ID IS NULL;