CREATE OR REPLACE TABLE SILVER.PATIENTS_CLEAN AS
SELECT DISTINCT
    SUBJECT_ID,
    GENDER,
    ANCHOR_AGE,
    ANCHOR_YEAR,
    ANCHOR_YEAR_GROUP,
    DOD
FROM BRONZE.PATIENTS
WHERE SUBJECT_ID IS NOT NULL;