CREATE OR REPLACE TABLE SILVER.ADMISSIONS_CLEAN AS
SELECT DISTINCT
    SUBJECT_ID,
    HADM_ID,
    ADMITTIME,
    DISCHTIME,
    DEATHTIME,
    ADMISSION_TYPE,
    ADMISSION_LOCATION,
    DISCHARGE_LOCATION,
    INSURANCE,
    LANGUAGE,
    MARITAL_STATUS,
    RACE
FROM BRONZE.ADMISSIONS
WHERE SUBJECT_ID IS NOT NULL
  AND HADM_ID IS NOT NULL;