CREATE OR REPLACE TABLE SILVER.ICUSTAYS_CLEAN AS
SELECT DISTINCT
    SUBJECT_ID,
    HADM_ID,
    STAY_ID,
    FIRST_CAREUNIT,
    LAST_CAREUNIT,
    INTIME,
    OUTTIME,
    LOS
FROM BRONZE.ICUSTAYS
WHERE SUBJECT_ID IS NOT NULL
  AND HADM_ID IS NOT NULL
  AND STAY_ID IS NOT NULL;