CREATE OR REPLACE TABLE SILVER.DIAGNOSES_CLEAN AS
SELECT
    d.SUBJECT_ID,
    d.HADM_ID,
    d.SEQ_NUM,
    d.ICD_CODE,
    d.ICD_VERSION,
    dd.LONG_TITLE AS DIAGNOSIS_TITLE
FROM BRONZE.DIAGNOSES_ICD d
LEFT JOIN BRONZE.D_ICD_DIAGNOSES dd
    ON d.ICD_CODE = dd.ICD_CODE
   AND d.ICD_VERSION = dd.ICD_VERSION
WHERE d.SUBJECT_ID IS NOT NULL
  AND d.HADM_ID IS NOT NULL;