CREATE OR REPLACE TABLE SILVER.INFECTION_DIAGNOSIS_CLEAN AS
SELECT
    SUBJECT_ID,
    HADM_ID,
    ICD_CODE,
    ICD_VERSION,
    DIAGNOSIS_TITLE
FROM SILVER.DIAGNOSES_CLEAN
WHERE LOWER(DIAGNOSIS_TITLE) LIKE '%sepsis%'
   OR LOWER(DIAGNOSIS_TITLE) LIKE '%infection%'
   OR LOWER(DIAGNOSIS_TITLE) LIKE '%pneumonia%'
   OR LOWER(DIAGNOSIS_TITLE) LIKE '%bacter%'
   OR LOWER(DIAGNOSIS_TITLE) LIKE '%urosepsis%';