CREATE OR REPLACE TABLE SILVER.LABEVENTS_SOFA_CLEAN AS
SELECT
    LABEVENT_ID,
    SUBJECT_ID,
    HADM_ID,
    SPECIMEN_ID,
    ITEMID,
    CHARTTIME,
    STORETIME,
    VALUE,
    VALUENUM,
    VALUEUOM,
    REF_RANGE_LOWER,
    REF_RANGE_UPPER,
    FLAG,
    PRIORITY,
    COMMENTS,
    ORDER_PROVIDER_ID,
    CASE
        WHEN ITEMID IN (50912, 52546) THEN 'renal_creatinine'
        WHEN ITEMID IN (50885, 53089) THEN 'liver_bilirubin'
        WHEN ITEMID IN (51265, 53189) THEN 'coag_platelets'
        WHEN ITEMID IN (50821, 52042) THEN 'resp_pao2'
        ELSE NULL
    END AS SOFA_COMPONENT
FROM BRONZE.LABEVENTS_SOFA
WHERE ITEMID IN (
    50912, 52546,
    50885, 53089,
    51265, 53189,
    50821, 52042
)
AND SUBJECT_ID IS NOT NULL
AND HADM_ID IS NOT NULL
AND CHARTTIME IS NOT NULL
AND VALUENUM IS NOT NULL;