CREATE OR REPLACE TABLE SILVER.ICU_COHORT_CLEAN AS
SELECT
    i.SUBJECT_ID,
    i.HADM_ID,
    i.STAY_ID,
    p.GENDER,
    p.ANCHOR_AGE,
    p.ANCHOR_YEAR,
    p.ANCHOR_YEAR_GROUP,
    p.DOD,
    a.ADMITTIME,
    a.DISCHTIME,
    a.DEATHTIME,
    a.ADMISSION_TYPE,
    a.ADMISSION_LOCATION,
    a.DISCHARGE_LOCATION,
    a.INSURANCE,
    a.LANGUAGE,
    a.MARITAL_STATUS,
    a.RACE,
    i.FIRST_CAREUNIT,
    i.LAST_CAREUNIT,
    i.INTIME,
    i.OUTTIME,
    i.LOS
FROM SILVER.ICUSTAYS_CLEAN i
LEFT JOIN SILVER.ADMISSIONS_CLEAN a
    ON i.SUBJECT_ID = a.SUBJECT_ID
   AND i.HADM_ID = a.HADM_ID
LEFT JOIN SILVER.PATIENTS_CLEAN p
    ON i.SUBJECT_ID = p.SUBJECT_ID
WHERE i.SUBJECT_ID IS NOT NULL
  AND i.HADM_ID IS NOT NULL
  AND i.STAY_ID IS NOT NULL;